apiVersion: apps/v1
kind: Deployment
metadata:
  name: flipkart-demo
  labels:
    app: flipkart
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flipkart
  template:
    metadata:
      labels:
        app: flipkart
    spec:
      containers:
      - name: flipkart
        image: kvnikhill/flipkart-demo:24
        ports:
        - containerPort: 3000
