apiVersion: apps/v1
kind: Deployment
metadata:
  name: Flipkart-Demo
  labels:
    app: Flipkart
spec:
  replicas: 3
  selector:
    matchLabels:
      app: Flipkart
  template:
    metadata:
      labels:
        app: Flipkart
    spec:
      containers:
      - name: Flipkart
        image: kvnikhill/flipkart-demo:24
        ports:
        - containerPort: 3000
