apiVersion: v1
kind: Service
metadata:
  name: flipkart-service
spec:
  selector:
    fapp.kubernetes.io/name: Flipkart
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: NodePort